### ISSUE TITLE
Clarification on Performance Reported in the Paper

### ISSUE THREAD

**Issue by seunghub** [xmed-lab/NumCLIP#1]
Hello,

Thank you for your inspiring work! I have two questions regarding your paper:

If I understand correctly, your framework employs two types of loss functions (CE-based FCRC and MAE). However, in your code, it seems that KL divergence is also used. When I ran your code, I obtained a test MAE of 2.0970 (w/ KL div) and 2.1222 (w/o KL div). Could you provide more information on how to reproduce the results reported in your paper?

In Table 1 and Table 4-all, the reported performances differ (2.08 vs. 2.11). Could you explain the reason for this discrepancy?

Thank you for your time, and I look forward to your response.

**Comment by duyao-art** [comment]
Thanks for your interest in our paper!
To reproduce the reported results, CE-based FCRC + KL-based FCRC + MAE loss should be employed. We present CE-based FCRC only in paper for simplicity.
The SOTA result should be 2.08. This should be a typo error. Thanks for noticing this.
